name = "DBF"
uuid = "05a0241d-af54-46e5-a412-7f757969bf0b"
authors = ["Nick Mayhall"]
version = "1.0.0-DEV"

[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
GraphPlot = "a2cc645c-3eea-5389-862e-a155d0052231"
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
ITensorMPS = "0d1a4710-d33b-49a5-8f18-73bdf49b47e2"
ITensors = "9136182c-28ba-11e9-034c-db9fb085ebd5"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
Karnak = "cd156443-31ad-4f6f-850f-a93ee5f75905"
KrylovKit = "0b1a1467-8014-51b9-945f-bf0ae24f4b77"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
LinearMaps = "7a12625a-238d-50fd-b39a-03d52299707e"
NetworkLayout = "46757867-2c16-5918-afeb-47bfcb05e46a"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
PauliOperators = "be646426-f34c-4536-b1d4-a45a9633e6db"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Polynomials = "f27b6e38-b328-58d1-80ce-0feddd5e7a45"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
StatProfilerHTML = "a8a75453-ed82-57c9-9e16-4cd1196ecbf5"

[compat]
BenchmarkTools = "1.6.0"
Colors = "0.13.1"
GraphPlot = "0.6.2"
Graphs = "1.13.1"
ITensorMPS = "0.3.23"
ITensors = "0.9.14"
JLD2 = "0.6.2"
Karnak = "1.2.0"
KrylovKit = "0.10.2"
LinearAlgebra = "1.11.0"
LinearMaps = "3.11.4"
NetworkLayout = "0.4.10"
Optim = "1.13.2"
OrderedCollections = "1.8.1"
PauliOperators = "2.0.0"
Plots = "1.41.1"
Polynomials = "4.1.0"
Printf = "1.11.0"
Random = "1.11.0"
StatProfilerHTML = "1.6.0"
julia = "1.11"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
